/**
 * Version information for fever-dream-sharpee
 * Auto-generated by sharpee - DO NOT EDIT
 */
export const STORY_VERSION = '2.0.0';
export const BUILD_DATE = '2026-09-12T05:54:23Z';
export const VERSION_INFO = { version: STORY_VERSION, buildDate: BUILD_DATE } as const;
